server:
  port: 1234
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  profiles:
    include: engine,common,iot,pipe

springdoc:
  swagger-ui:
    path: "/docs"
    enabled: true
  api-docs:
    path: "/swagger.json"
    enabled: true

knife4j:
  enable: true
  openapi:
    title: "Api Documentation"
    description: "Api Documentation"
    email: "512742341@qq.com"
    concat: "wbs"
    version: "v1.0"
    group:
      engine:
        group-name: "engine"
        api-rule: package
        api-rule-resources:
          - "com.wbs.engine"
      common:
        group-name: "common"
        api-rule: package
        api-rule-resources:
          - "com.wbs.common"
      pipe:
        group-name: "pipe"
        api-rule: package
        api-rule-resources:
          - "com.wbs.pipe"

logging:
  config: "classpath:logback-spring.xml"
  file:
    path: logs
