test1: [ { id: 1,name: wbs },{ id: 2,name: wqy } ]

test2:
  - id: 1
    name: wbs
  - id: 2
    name: wqy

test3: haha

test4:
  a: 123

test5: aaaaaa

test6: ${test5}/ + hahahhaha

test7:
  id: 1
  name: "wbs"
