huawei:
  ak: "WPC9R5I3AQAYINPQRAEG"
  sk: "yyayWWTluTbsF45Q0xWhDPAUZZng8pyxPa1114NW"
  region: "cn-north-4"

ali:
  accessKeyId: "LTAImYBSVfLTwohp"
  accessKeySecret: "nac27NrdgEllUXGLw0DXeQOg1zUOJ9"
  endpoint: "iot.cn-shanghai.aliyuncs.com"

ctwing:
  aaa: "HxC7tM2w7WuJv0pVJ6Y3LYAKsmY="

onenet:
  masterKey: "HxC7tM2w7WuJv0pVJ6Y3LYAKsmY="